/*
 * This source file was generated by the Gradle 'init' task
 */
package gateway.service;

import gateway.service.proxy.NettyServer;
import gateway.service.utils.AppConfigs;
import gateway.service.utils.Common;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
  private static final Logger logger = LoggerFactory.getLogger(App.class);

  public static void main(String[] args) throws Exception {
    logger.info("Starting Gateway App...");
    Common.validateInitArgs();
    AppConfigs.refreshAppConfigs();
    new NettyServer().start();
    logger.info("Started Gateway App...");
  }
}
