/*
 * This source file was generated by the Gradle 'init' task
 */
package gateway.service;

import gateway.service.utils.Common;
import gateway.service.utils.Constants;
import gateway.service.utils.Routes;
import java.util.List;
import java.util.Map;

public class App {

  public static void main(String[] args) {
    validateInitArgs();
    Routes.refreshRoutes();
  }

  private static void validateInitArgs() {
    final Map<String, String> properties = Common.getAllSystemEnvProperties();
    final List<String> requiredEnvProperties =
        Constants.ENV_KEY_NAMES.stream().filter(key -> !Constants.ENV_PORT.equals(key)).toList();
    final List<String> errors =
        requiredEnvProperties.stream().filter(key -> properties.get(key) == null).toList();
    if (!errors.isEmpty()) {
      throw new IllegalStateException(
          "One or more environment configurations could not be accessed...");
    }
  }
}
